// PSEUDOCODE - README
// BUILD APP THAT WILL RUN AS NODE CLI THAT TAKES IN (GATHER) INFORMATION ABOUT EMPLOYEES AND GENERATE A HTML WEBPAGE THAT DIPLAYS SUMMARIES FOR EACH PERSON
        // BUILD SE TEAM GENERATOR CLI APP
            // PROMPT USER FOR INFO ABOUT TEAM MANAGER AND ANY INFO ON TEAM MEMBERS
            // CAN IMPUT ANY NUMBER OF TEAM MEMBERS
            // MIX OF ENGINEERS AND INTERNS
            // WHEN DONE BUILDING - APP WILL CREATE HTML FILE THAT DISPLAYS NICELY FORMATTED ROSTER BASED ON INFO PROVIDED BY USER
        // GENERATE WEBPAGE THAT DISPLAY TEAM'S BASIC INFO TO HAVE QUICK ACCESS TO THEIR CONTACT INFO
        // MAKE TESTS PASS

// USE INQUIRER - ASK USER FOR EMAIL, ID. AND OTHER INFO PERTAINING TO ROLE IN COMPANY
    // INTERN - SCHOOL
    // ENGINEER - GITHUB USERNAME
// RUN NPM INSTALL
    // DEPENDENCIES - JEST, INQUIRER

// WORKFLOW
    // RUN TEST - USE "NPM RUN TEST"
    // CREATE/UPDATE CLASSES TO PASS TEST CASE
    // REPEAT

// DIRECTORY STRUCTURE?? - MORE RESEARCH

// HINTS
    // CREATE MANY HTML TEMPLATES FOR EACH TYPE OF USER (MAIN/ENGINEER/INTERN/MANAGER)
        // ADD PLACEHOLDER CHARACTER THAT HELPS PROGRAM ID WHERE DYNAMIC MARKUP BEGINS AND ENDS
    // MAKE METHODS AS SIMPLE AS POSSIBLE
    // DIFF EMPLOYEES SHOULD INHERIT SOME METHODS AND PROPERTIES FROM BASE CLASS OF 'EMPLOYEE.'

// FINISHING PRODUCT - FUNCTIONAL APP, GITHUB REPO WITH README, USER GENERATING HTML WITH INFO ON TEAM, PASS TESTS
    // HAVE CLASS "EMPLOYEE". "MANAGER", "ENGINEER", "INTERN"
        // EMPLOYEE - PARENT CLASS
            // NAME
            // ID
            // EMAIL
            // GETNAME()
            // GETID ()
            // GET EMAIL ()
            // GETROLE() - RETURNS 'EMPLOYEE'
        // MANAGER - SAME AS 'EMPLOYEE' PLUS MORE
            // OFFICENUMBER
            // GETROLE() - OVERRIDEN TO RETURN 'MANAGER'
        // ENGINEER - SAME AS 'EMPLOYEE' PLUS MORE
            // GITHUB USERNAME
            // GETGITHUB()
            // GETROLE() - OVERRIDEN TO RETURN 'ENGINEER'
        // INTERN - SAME AS 'EMPLOYEE' PLUS MORE
            // SCHOOL
            // GETSCHOOL()
            // GETROLE() - OVERRIDEN TO RETURN 'INTERN'
    // PROMPT USER TO BUILD ENGINEERING TEAM - MANAGER, AND ANY # ENGINEERS AND INTERNS
    // GENERATE HTML PAGE IN 'OUTPUT DIRECTORY' AND IS NICELY FORMATTED TEAM ROSTER
        // DISPLAY NAME, ROLE, ID, ROLE-SPECIFIC PROPERTY

// BONUS
    // DATA VALIDATION
    // ADDING APP TO PORTFOLIO

// SUBMISSION
    // URL OF GITHUB REPO
    // VIDEO OF FUNCTIONALITY


// PSEUDOCODE APPLICATION
// NODE FILENAME ON TERMINAL
// INQUIRER QUESTIONS - FOR LOOP
        // ASK FOR ENPLOYEE INFO
            // IF USER INPUTS MANAGER
                // MANAGER SUBCLASS QUESTIONS WILL APPEAR
                    // ANSWER QUESTIONS
                    // RETURN TO EMPLOYEE TO ADD MORE 
            // IF USER INPUTS ENGINEER
                // ENGINEER SUBCLASS QUESTIONS WILL APPEAR
                    // ANSWER QUSTIONS
                    // RETURN TO EMPLOYEE TO ADD MORE
            // IF USER INPUTS INTERN
                // INTERN SUBCLASS QUESTIONS WILL APPEAR
                    // ANSWER QUSTIONS
                    // RETURN TO EMPLOYEE TO ADD MORE 
            // IF THERE ARE NO MORE EMPLOYEES TO ENTER
                // USE GETROLE() TO FINISH
        // CREATE HTML FILE WITH FORMATTED TEAM ROSTER
// INFORMATION FROM INQUIRER USED TO GENERATE INDEX FILE
    // USE WRITEFILE FUNCTION FOR ONE INDEX FILE

